[label]
PROP_TABLE_HEAD_LABEL = "Label"
PROP_TABLE_HEAD_VALUE = "Value"
PROP_TABLE_MASS_LABEL = "Mass"
PROP_TABLE_DIMS_LABEL = "Dimensions (WxDxH)"
PROP_TABLE_COST_LABEL = "Cost"
PROP_TABLE_TAGS_LABEL = "Tags"
PROP_TABLE_FILE_LABEL = "File"
LOGIC_TABLE_HEAD_TYPE = "Type"
LOGIC_TABLE_HEAD_LABEL = "Label"
LOGIC_TABLE_HEAD_DESC = "Description"
DEPRECATED_TEXT = "This component is deprecated."

SHEET_HEAD_NAME = "Name"
SHEET_HEAD_FILE = "File"
SHEET_HEAD_CATEGORY = "Category"
SHEET_HEAD_TAGS = "Tags"
SHEET_HEAD_DEPRECATED = "Deprecated"
SHEET_HEAD_MASS = "Mass"
SHEET_HEAD_COST = "Cost"
SHEET_HEAD_WIDTH = "Width"
SHEET_HEAD_DEPTH = "Depth"
SHEET_HEAD_HEIGHT = "Height"
SHEET_HEAD_SDESC = "Short Description"
SHEET_HEAD_DESC = "Description"
