[label]
DOCUMENT_PROP_MASS = "Mass: {}"
DOCUMENT_PROP_MASS_PARENT = "Parent Mass: {}"
DOCUMENT_PROP_MASS_CHILD = "Child Mass: {}"
DOCUMENT_PROP_DIMS = "Dimensions (WxDxH): {}"
DOCUMENT_PROP_DIMS_PARENT = "Parent Dimensions (WxDxH): {}"
DOCUMENT_PROP_DIMS_CHILD = "Child Dimensions (WxDxH): {}"
DOCUMENT_PROP_COST = "Cost: ${}"
DOCUMENT_PROP_TAGS = "Tags: {}"
DOCUMENT_PROP_FILE = "File: {}"
DOCUMENT_PROP_FILE_PARENT = "Parent File: {}"
DOCUMENT_PROP_FILE_CHILD = "Child File: {}"
DOCUMENT_LOGIC_TABLE_NORMAL_HEAD_TYPE = "Type"
DOCUMENT_LOGIC_TABLE_NORMAL_HEAD_LABEL = "Label"
DOCUMENT_LOGIC_TABLE_NORMAL_HEAD_DESC = "Description"
DOCUMENT_LOGIC_TABLE_MULTIBODY_HEAD_BODY = "Body"
DOCUMENT_LOGIC_TABLE_MULTIBODY_HEAD_TYPE = "Type"
DOCUMENT_LOGIC_TABLE_MULTIBODY_HEAD_LABEL = "Label"
DOCUMENT_LOGIC_TABLE_MULTIBODY_HEAD_DESC = "Description"
DOCUMENT_LOGIC_TABLE_MULTIBODY_BODY_PARENT = "Parent"
DOCUMENT_LOGIC_TABLE_MULTIBODY_BODY_CHILD = "Child"
DOCUMENT_DEPRECATED_TEXT = "This component is deprecated."
DOCUMENT_ORPHAN_TEXT = "This component is orphan. No parent component found."
SHEET_HEAD_NAME = "Name"
SHEET_HEAD_FILE_PARENT = "Parent File"
SHEET_HEAD_FILE_CHILD = "Child File"
SHEET_HEAD_CATEGORY = "Category"
SHEET_HEAD_TAGS = "Tags"
SHEET_HEAD_DEPRECATED = "Deprecated"
SHEET_HEAD_ORPHAN = "Orphan"
SHEET_HEAD_COST = "Cost"
SHEET_HEAD_MASS_TOTAL = "Total Mass"
SHEET_HEAD_MASS_PARENT = "Parent Mass"
SHEET_HEAD_MASS_CHILD = "Child Mass"
SHEET_HEAD_DIMS_TOTAL_WIDTH = "Total Width"
SHEET_HEAD_DIMS_TOTAL_DEPTH = "Total Depth"
SHEET_HEAD_DIMS_TOTAL_HEIGHT = "Total Height"
SHEET_HEAD_DIMS_PARENT_WIDTH = "Parent Width"
SHEET_HEAD_DIMS_PARENT_DEPTH = "Parent Depth"
SHEET_HEAD_DIMS_PARENT_HEIGHT = "Parent Height"
SHEET_HEAD_DIMS_CHILD_WIDTH = "Child Width"
SHEET_HEAD_DIMS_CHILD_DEPTH = "Child Depth"
SHEET_HEAD_DIMS_CHILD_HEIGHT = "Child Height"
SHEET_HEAD_SDESC = "Short Description"
SHEET_HEAD_DESC = "Description"
