[label]
DOCUMENT_NORMAL_PROP_TABLE_HEAD_LABEL = "Label"
DOCUMENT_NORMAL_PROP_TABLE_HEAD_VALUE = "Value"
DOCUMENT_NORMAL_PROP_TABLE_MASS_LABEL = "Mass"
DOCUMENT_NORMAL_PROP_TABLE_DIMS_LABEL = "Dimensions (WxDxH)"
DOCUMENT_NORMAL_PROP_TABLE_COST_LABEL = "Cost"
DOCUMENT_NORMAL_PROP_TABLE_TAGS_LABEL = "Tags"
DOCUMENT_NORMAL_PROP_TABLE_FILE_LABEL = "File"
DOCUMENT_NORMAL_LOGIC_TABLE_HEAD_TYPE = "Type"
DOCUMENT_NORMAL_LOGIC_TABLE_HEAD_LABEL = "Label"
DOCUMENT_NORMAL_LOGIC_TABLE_HEAD_DESC = "Description"
DOCUMENT_MULTIBODY_PROP_TABLE_HEAD_LABEL = "Label"
DOCUMENT_MULTIBODY_PROP_TABLE_HEAD_PARENT = "Parent"
DOCUMENT_MULTIBODY_PROP_TABLE_HEAD_CHILD = "Child"
DOCUMENT_MULTIBODY_PROP_TABLE_HEAD_TOTAL = "Total"
DOCUMENT_MULTIBODY_PROP_TABLE_MASS_LABEL = "Mass"
DOCUMENT_MULTIBODY_PROP_TABLE_DIMS_LABEL = "Dimensions (WxDxH)"
DOCUMENT_MULTIBODY_PROP_TABLE_COST_LABEL = "Cost"
DOCUMENT_MULTIBODY_PROP_TABLE_COST_CHILD = "-"
DOCUMENT_MULTIBODY_PROP_TABLE_COST_TOTAL = "-"
DOCUMENT_MULTIBODY_PROP_TABLE_TAGS_LABEL = "Tags"
DOCUMENT_MULTIBODY_PROP_TABLE_TAGS_CHILD = "-"
DOCUMENT_MULTIBODY_PROP_TABLE_TAGS_TOTAL = "-"
DOCUMENT_MULTIBODY_PROP_TABLE_FILE_LABEL = "File"
DOCUMENT_MULTIBODY_PROP_TABLE_FILE_TOTAL = "-"
DOCUMENT_MULTIBODY_LOGIC_TABLE_HEAD_BODY = "Body"
DOCUMENT_MULTIBODY_LOGIC_TABLE_HEAD_TYPE = "Type"
DOCUMENT_MULTIBODY_LOGIC_TABLE_HEAD_LABEL = "Label"
DOCUMENT_MULTIBODY_LOGIC_TABLE_HEAD_DESC = "Description"
DOCUMENT_MULTIBODY_LOGIC_TABLE_BODY_PARENT = "Parent"
DOCUMENT_MULTIBODY_LOGIC_TABLE_BODY_CHILD = "Child"
DOCUMENT_COMMON_DEPRECATED_TEXT = "This component is deprecated."
DOCUMENT_COMMON_ORPHAN_TEXT = "This component is orphan. No parent component found."

SHEET_HEAD_NAME = "Name"
SHEET_HEAD_FILE_PARENT = "Parent File"
SHEET_HEAD_FILE_CHILD = "Child File"
SHEET_HEAD_CATEGORY = "Category"
SHEET_HEAD_TAGS = "Tags"
SHEET_HEAD_DEPRECATED = "Deprecated"
SHEET_HEAD_ORPHAN = "Orphan"
SHEET_HEAD_COST = "Cost"
SHEET_HEAD_MASS_TOTAL = "Total Mass"
SHEET_HEAD_MASS_PARENT = "Parent Mass"
SHEET_HEAD_MASS_CHILD = "Child Mass"
SHEET_HEAD_DIMS_TOTAL_WIDTH = "Total Width"
SHEET_HEAD_DIMS_TOTAL_DEPTH = "Total Depth"
SHEET_HEAD_DIMS_TOTAL_HEIGHT = "Total Height"
SHEET_HEAD_DIMS_PARENT_WIDTH = "Parent Width"
SHEET_HEAD_DIMS_PARENT_DEPTH = "Parent Depth"
SHEET_HEAD_DIMS_PARENT_HEIGHT = "Parent Height"
SHEET_HEAD_DIMS_CHILD_WIDTH = "Child Width"
SHEET_HEAD_DIMS_CHILD_DEPTH = "Child Depth"
SHEET_HEAD_DIMS_CHILD_HEIGHT = "Child Height"
SHEET_HEAD_SDESC = "Short Description"
SHEET_HEAD_DESC = "Description"
