[template]
action_axis_ui_navigate_x = "pad 1 axis 1"
action_axis_ui_navigate_y = "pad 1 axis 2"
action_ui_select = "pad 1 button 1"
action_ui_back = "pad 1 button 2"
action_ui_context = "pad 1 button 3"
action_ui_tab_left = "pad 1 button 5"
action_ui_tab_right = "pad 1 button 6"
action_axis_move_x = "pad 1 axis 1"
action_axis_move_y = "pad 1 axis 2"
action_axis_view_x = "pad 1 axis 3"
action_axis_view_y = "pad 1 axis 4"
action_up = "w"
action_down = "s"
action_left = "a"
action_right = "d"
action_crouch = "lctrl"
action_jump = "space"
action_sprint = "lshift"
action_walk = "unassigned"
action_interact_left = "q"
action_interact_right = "e"
action_equipment_use = "lmb"
action_equipment_secondary = "r"
action_equipment_drop = "backspace"
action_equipment_cycle_next = "v"
action_equipment_cycle_prev = "c"
action_use_seat = "f"
action_return_to_workbench = "b"
action_axis_1 = "pad 1 axis 1"
action_axis_2 = "pad 1 axis 2"
action_axis_3 = "pad 1 axis 3"
action_axis_4 = "pad 1 axis 4"
action_axis_5 = "pad 1 axis 5"
action_axis_6 = "pad 1 axis 6"
action_axis_7 = "pad 1 axis 7"
action_axis_8 = "pad 1 axis 8"
action_throttle_up = "up"
action_throttle_down = "down"
action_pedal_left = "left"
action_pedal_right = "right"
action_trim = "lalt"
action_hide_seat_ui = "h"
action_pad_look_left = "unassigned"
action_pad_look_right = "unassigned"
action_pad_look_down = "unassigned"
action_pad_look_up = "unassigned"
action_free_view = "pad 1 button 5"
action_trigger = "space"
action_hotkey_1 = "1"
action_hotkey_2 = "2"
action_hotkey_3 = "3"
action_hotkey_4 = "4"
action_hotkey_5 = "5"
action_hotkey_6 = "6"
action_hotkey_7 = "unassigned"
action_hotkey_8 = "unassigned"
action_hotkey_9 = "unassigned"
action_hotkey_10 = "unassigned"
action_hotkey_11 = "unassigned"
action_hotkey_12 = "unassigned"
action_hotkey_13 = "unassigned"
action_hotkey_14 = "unassigned"
action_hotkey_15 = "unassigned"
action_hotkey_16 = "unassigned"
action_hotkey_17 = "unassigned"
action_hotkey_18 = "unassigned"
action_hotkey_19 = "unassigned"
action_hotkey_20 = "unassigned"
action_hotkey_21 = "unassigned"
action_hotkey_22 = "unassigned"
action_hotkey_23 = "unassigned"
action_hotkey_24 = "unassigned"
action_hotkey_25 = "unassigned"
action_hotkey_26 = "unassigned"
action_hotkey_27 = "unassigned"
action_hotkey_28 = "unassigned"
action_hotkey_29 = "unassigned"
action_hotkey_30 = "unassigned"
action_hotkey_31 = "unassigned"
action_hotkey_32 = "unassigned"
action_hotkey_33 = "unassigned"
action_hotkey_34 = "unassigned"
action_hotkey_35 = "unassigned"
action_hotkey_36 = "unassigned"
action_hotkey_37 = "unassigned"
action_hotkey_38 = "unassigned"
action_hotkey_39 = "unassigned"
action_hotkey_40 = "unassigned"
action_hotkey_41 = "unassigned"
action_hotkey_42 = "unassigned"
action_hotkey_43 = "unassigned"
action_hotkey_44 = "unassigned"
action_hotkey_45 = "unassigned"
action_hotkey_46 = "unassigned"
action_hotkey_47 = "unassigned"
action_hotkey_48 = "unassigned"
action_camera_mode = "tab"
action_zoom = "rmb"
action_photo_crane_up = "up"
action_photo_crane_down = "down"
action_photo_slow = "lctrl"
action_photo_fast = "lshift"
action_photo_very_fast = "lalt"
action_photo_pause = "p"
action_photo_hide = "h"
action_photo_reset = "r"
action_player_list = "`"
action_emote_wheel = "unassigned"
action_quick_chat = "enter"
action_voice_chat = "'"
action_pause = "pad 1 button 8"
action_map = "m"
action_creative_menu = "unassigned"
action_photo_mode = "unassigned"
action_labels_detailed = "page up"
action_noclip = "home"
action_editor_camera_forward = "w"
action_editor_camera_back = "s"
action_editor_camera_left = "a"
action_editor_camera_right = "d"
action_editor_camera_up = "e"
action_editor_camera_down = "q"
action_editor_camera_zoom_in = "="
action_editor_camera_zoom_out = "-"
action_editor_camera_set_origin = "f"
action_editor_rotate_x = "j"
action_editor_rotate_y = "k"
action_editor_rotate_z = "l"
action_editor_flip_x = "u"
action_editor_flip_y = "i"
action_editor_flip_z = "o"
action_editor_show_rotation_ui = "p"
action_editor_toggle_eraser = "x"
action_editor_show_hide_vehicle = "h"
action_editor_spawn_vehicle = "enter"
